name: Deploy to EC2 with Docker (GHCR)

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to GHCR
        run: echo ${{ secrets.GHCR_TOKEN }} | docker login ghcr.io -u RavjeetChahal --password-stdin

      - name: Build and push Docker image
        run: |
          IMAGE_NAME=ghcr.io/${{ github.repository }}/my-app:latest
          docker build -t $IMAGE_NAME .
          docker push $IMAGE_NAME

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            IMAGE_NAME=ghcr.io/${{ github.repository }}/my-app:latest
            echo ${{ secrets.GHCR_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
            docker pull $IMAGE_NAME
            docker stop my-app || true
            docker rm my-app || true
            docker run -d --name my-app \
              -p 3000:3000 \
              -e OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }} \
              -e CORS_ALLOW_ORIGINS=${{ secrets.CORS_ALLOW_ORIGINS }} \
              -e FIREBASE_SERVICE_ACCOUNT=${{ secrets.FIREBASE_SERVICE_ACCOUNT }} \
              -e FIREBASE_DATABASE_URL=${{ secrets.FIREBASE_DATABASE_URL }} \
              $IMAGE_NAME